[package]
name = "gba-emulator-mobile"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies.gba-emulator]
path = "../"

[build-dependencies]
swift-bridge-build = "0.1"

[dependencies]
swift-bridge = "0.1"
zstd = "0.13"
ringbuf="0.4.8"